### ISSUE TITLE
Running issue

### ISSUE THREAD

**Issue by aricction** [Soumya-Dey/Razorpay-payment-gateway-react-node#1]
how to run this on my system

**Comment by Soumya-Dey** [comment]
The repo was not in sync with the blog. Sorry for that. It is now in sync with the blog post in Dev.to. You may need to clone the repo again in your local machine.
For running this on your system replace the Razorpay keys inside `env.js` file with your keys and use your own `MongoDB uri`.

Then you can run `npm i -g concurrently` to install concurrently globally in your machine, which is used here to run the backend and frontend with a single command.
Then you can run the command `npm run dev` to start both the front and back end servers.

**Comment by aricction** [comment]
After installing npm i -g concurrently and running npm run dev ,it still doesnt opens up the software in localhost , it show error '

[1] > razorpay-test@1.0.0 client
[1] > npm run start --prefix client
[1]
[0]
[0] > razorpay-test@1.0.0 server
[0] > nodemon server.js
[0]
[0] 'nodemon' is not recognized as an internal or external command,
[0] operable program or batch file.
[0] npm run server exited with code 1
[1]
[1] > client@0.1.0 start
[1] > react-scripts start
[1]
[1] 'react-scripts' is not recognized as an internal or external command,
[1] operable program or batch file.
[1] npm run client exited with code 1

**Comment by Soumya-Dey** [comment]
From the errors, I can see that
- You haven't installed the dependencies yet.
- **nodemon** is not installed in your system.

1. To run any project cloned from a repo, first, you have to run the command `npm i` from **the root of the project folder[the folder where the `server.js` file is]** to install all the dependencies locally.
2. Then go inside the `client` folder by the command `cd client`, and run the command `npm i` to install the React js dependencies.
1. For installing **nodemon** run the command `npm i -g nodemon`
